{% set version = "1.5.3" %}

package:
  name: simple-build-system
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/simple-build-system/simple_build_system-{{ version }}.tar.gz
  #NB: get sha256 from https://pypi.org/project/simple-build-system/#files
  sha256: 8e9e22ccdd7972a2d708c76885a448405eef265d648536eee640bc2535150037

build:
  noarch: python
  number: 0
  entry_points:
    - sb = _simple_build_system._cli:main
    - unwrapped_simplebuild = _simple_build_system._cli:unwrapped_main
    - sbenv = _simple_build_system._cli:sbenv_main
    - sbrun = _simple_build_system._cli:sbrun_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-git-versioning
    - setuptools
  run:
    - python >={{ python_min }}
    #NB: Once oldest supported python is 3.11, we can remove tomli:
    - tomli
    - pybind11 >=2.10.4
    - cmake >=3.24.2
    - make
    - numpy

test:
  requires:
    # Note: The actual tests are defined in run_test.sh
    - python {{ python_min }}
    - c-compiler
    - cxx-compiler
    - pip

about:
  home: https://mctools.github.io/simplebuild
  summary: A very simple to use build system for scientific projects with C++/Python.
  description: |
    A very simple to use build system for projects with primarily C++/Python
    code, intended for usage by scientific developers without a strong
    SW-engineering background
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://mctools.github.io/simplebuild
  dev_url: https://github.com/mctools/simplebuild

extra:
  recipe-maintainers:
    - tkittel
