{% set version = "0.0.31" %}

#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: simple-build-system
  version: {{ version }}

source:
  url: https://github.com/mctools/simplebuild/archive/v{{ version }}.tar.gz
  sha256: 1e59052d7ecbedc4675976a286c87f9338802d4d4a653e31dd8e4e8bc24bbf1e

build:
  skip: true  # [win or py<39]
  number: 0
  entry_points:
    - sb = _simple_build_system._cli:main
    - unwrapped_simplebuild = _simple_build_system._cli:unwrapped_main
    - sbenv = _simple_build_system._cli:sbenv_main
    - sbrun = _simple_build_system._cli:sbrun_main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - tomli  # [py<311]
    - pybind11 >=2.10.4
    - cmake >=3.24.2
    - make
    - numpy

test:
  requires:
    # Note: The actual tests are defined in run_test.sh
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pip

about:
  home: https://mctools.github.io/simplebuild
  summary: A very simple to use build system for scientific projects with C++/Python.
  description: |
    A very simple to use build system for projects with primarily C++/Python
    code, intended for usage by scientific developers without a strong
    SW-engineering background
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://mctools.github.io/simplebuild
  dev_url: https://github.com/mctools/simplebuild

extra:
  recipe-maintainers:
    - tkittel
