{% set version = "1.0.1" %}

#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: simple-build-system
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simple-build-system/simple-build-system-{{ version }}.tar.gz
  sha256: 953e5b47e3e7bd369104b3a66aba1023d1bbb118e0917cc72b5ae0d1084c59c0

build:
  noarch: python
  number: 0
  entry_points:
    - sb = _simple_build_system._cli:main
    - unwrapped_simplebuild = _simple_build_system._cli:unwrapped_main
    - sbenv = _simple_build_system._cli:sbenv_main
    - sbrun = _simple_build_system._cli:sbrun_main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-git-versioning
    - setuptools
  run:
    - python >=3.8
    #NB: Once oldest supported python is 3.11, we can remove tomli:
    - tomli
    - pybind11 >=2.10.4
    - cmake >=3.24.2
    - make
    - numpy

test:
  requires:
    # Note: The actual tests are defined in run_test.sh
    - c-compiler
    - cxx-compiler
    - pip

about:
  home: https://mctools.github.io/simplebuild
  summary: A very simple to use build system for scientific projects with C++/Python.
  description: |
    A very simple to use build system for projects with primarily C++/Python
    code, intended for usage by scientific developers without a strong
    SW-engineering background
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://mctools.github.io/simplebuild
  dev_url: https://github.com/mctools/simplebuild

extra:
  recipe-maintainers:
    - tkittel
